#+HUGO_BASE_DIR: .
#+HUGO_SECTION: post
#+hugo_weight: auto
#+STARTUP: logdone

#+BEGIN: columnview :hlines 1 :id "66a454c4-1a79-45d3-8bf3-3fdf38f27f21"
|                | Total time | Today |
|----------------+------------+-------|
| Immersion time |      11:29 |  0:21 |
#+END:

* Blog
** DONE How to develop a better nose for copy?
CLOSED: [2021-06-09 Wed 14:47]
:PROPERTIES:
:AUTHOR: Srđan /surgeon/ Mišić
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :subtitle "Here's what's wrong about the second most common piece of advice given to new copywriters."
:EXPORT_FILE_NAME: how-to-develop-a-better-nose-for-copy--so-you-can-smell-it-like-eugene-schwartz-did
:END:

When new copywriters ask how to get better, the first piece of advice they will hear is to write more copy, which is OK. The second piece of advice they'll hear is more dangerous: to read more copy.

Eager to improve, aspiring copywriters will start reading and hand-copying the best ads from the best copywriters who ever lived. Or maybe they'll read and hand-copy the ads that are working in the market today. Or perhaps both.

On it's own this won't work. It is like telling an aspiring sommelier that the best way to develop a sophisticated palate is too drink as much wine as possible.

# ^needs a new lead, something about famous copywriters urging you to read ads, but how it doesn't help if you don't train your taste buds.  One of the most often repeated advice given to aspiring copywriters is that they should spend as much time as possible reading and even copying successful ads.

If our wannabe sommelier listened to such advice he'd soon turn into a sad drunk.

Same goes for copy. If you mindlessly read or hand-copy you'll only turn into a dysfunctional copy addict living in your own world divorced from reality.

What you need to do is train your receptors. You need to develop a sense of how good copy tastes like.

It tastes like Belgian beer.

- The malty sweetness comes from the reader imagining the satisfaction of a desire.
- The slight hoppy bitterness the reader feels from not having satisfied it yet.
- The pleasant, comforting inner warmth is caused by the prospect's belief, the inner-assurance that the satisfaction is within reach.

Before you start reading a piece of copy, put yourself into your reader's shoes like a method actor.

As you begin to read, feel the slight hoppy twinge, the bitterness of FOMO and urgency. Don't just sit there with a blank face like you received a Botox injection. Actually let yourself wince whenever the copy prods you by bringing up a burning problem or pain.
{{<sidenote>}} Did you know that Botox injections actually decrease the strength of emotional experiences? So says [[https://psycnet.apa.org/record/2010-09991-012][this study]].  {{< /sidenote >}}

Finally, savor the alcoholic warmth that comes from the proof elements in the copy. The verbal demonstrations of the product in action. The third-party endorsements. The facts and figures that support the promises. Let them all fill your stomach with a sense of ease and comfort, and -- most importantly -- a new-found zest for taking action!

All this is to say: don't just read copy in big skimming gulps. Like too much wine or beer, it will only intoxicate you into false confidence.

You have to learn to swirl it, sniff it, savor it, and pick out and discern all the different flavors and how they come together into liquid desire.
