#+HUGO_BASE_DIR: .
#+HUGO_SECTION: post
#+hugo_weight: auto
#+STARTUP: logdone

#+BEGIN: columnview :hlines 1 :id "66a454c4-1a79-45d3-8bf3-3fdf38f27f21"
|                | Total time | Today |
|----------------+------------+-------|
| Immersion time |      11:29 |  0:21 |
#+END:

* Blog
** DONE How to develop a better nose for copy?
CLOSED: [2021-06-09 Wed 14:47]
:PROPERTIES:
:AUTHOR: Srđan /surgeon/ Mišić
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :subtitle "So you can smell it like Eugene Schwarz did"
:EXPORT_FILE_NAME: how-to-develop-a-better-nose-for-copy--so-you-can-smell-it-like-eugene-schwartz-did
:END:

You don't become a somellier by drinking as much wine as you can, and you don't become a copy connoseiur by reading and rewriting as much copy as you can.

# ^needs a new lead, something about famous copywriters urging you to read ads, but how it doesn't help if you don't train your taste buds.  One of the most often repeated advice given to aspiring copywriters is that they should spend as much time as possible reading and even copying succesful ads.

But this is like telling an aspiring sommelier that the best way to develop a sophisticated palate is too drink as much wine as possible, which would only turn our wannabe somellier into a sad drunk.

Same goes for copy. If you mindlessly read copy you'll only turn into a disfunctional copy addict.

So you need to train your receptors. You need to develop a sense of how good copy tastes like.

*** It tastes like Belgian beer

- The sweetness comes from the reader imagining the satisfaction of a desire.
- The slight bitterness he feels from not having satisfied it yet.
- The pleasant, comforting inner warmth is caused by the prospect's belief, the inner-assurance -- that his satisfaction is within reach.

Use this as a synesthetic (means when one sense mixes with another) aid when reading copy.   THIS PART NEEDS DEVELOPMENT:
Let all the verbalization and intensification hit your tongue like that bready belgian sweet malt.

Feel the slight hoppy twinge of the bitterness of FOMO and urgency.

And let the alcoholic warmth of proof, concentration, and gradualization fill your stomach with ease and comfort.  CONCL:   Don't read copy in big skimming gulps.  Like too much wine or beer, it will only intoxicate you into false confidence.

You have to learn to swirl it, sniff it, savor it, and pick out and discern all the different flavors and how they come together into liquid desire.
