baseurl = "/"
languageCode = "en-us"
title = "Srđan Mišić"
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
enableEmoji = true
footnotereturnlinkcontents = "↩"


[module]
  [[module.imports]]
    path = "/Users/srdjanmisic/dropbox/90-99 Professional/96 Personal Website/themes/typographical-hugo"


[permalinks]
    post = "/post/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 1
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 2
[[menu.feed]]
    name = "Subscribe"
    url = "/index.xml"

[params]
    description = "Personal website of Srđan Mišić."
    footer = "Get in touch: supersrdjan (at) gmail.com"
    custom_css = ["css/theme-override.css"]

# If you want to use Fathom (https://usefathom.com) for analytics, add this section
[params.fathomAnalytics]
    siteID = "ABCDE"
    # Default value is cdn.usefathom.com, overwrite this if you are self-hosting
    serverURL = "analytics.example.com"

