baseurl = "/"
languageCode = "en-us"
title = "Srđan Mišić"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
enableEmoji = true
footnotereturnlinkcontents = "↩"
publishDir = "public"


[permalinks]
    post = "/post/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 1
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 2
[[menu.feed]]
    name = "Subscribe"
    url = "/index.xml"


[params.dropCap]
  enable = true

[params]
    description = "Personal website of Srđan Mišić."
    footer = "Get in touch: supersrdjan (at) gmail.com"
    custom_css = ["css/theme-override.css"]
    accentColour = "#9be5aa"
