baseurl = "/"
languageCode = "en-us"
title = "Srđan Mišić"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
enableEmoji = true
footnotereturnlinkcontents = "↩"
publishDir = "public"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 2
[[menu.main]]
    name = "Posts"
    url = "/post/"
    weight = 1


[params.dropCap]
  enable = true
  fontSize = "5.5em"

[params]
    description = "Personal website of Srđan Mišić."
    footer = "Get in touch: supersrdjan (at) gmail.com"
    custom_css = ["css/theme-override.css"]
    accentColour = "#9be5aa"
    fontUrl = "https://fonts.googleapis.com/css2?family=IBM+Plex+Mono&family=IBM+Plex+Sans:wght@400;700&family=IBM+Plex+Serif:ital,wght@0,400;0,600;0,700;1,400;1,600;1,700&family=Literata&display=swap"

    SerifFont = "IBM Plex Serif"
    SecondarySerifFont = "IBM Plex Serif"
    SansSerifFont = "IBM Plex Sans"
    MonospaceFont = "IBM Plex Mono"
